import type { Metadata } from 'next'

import 'normalize.css/normalize.css'
import '@radix-ui/themes/styles.css'
import './globals.scss'

import { Providers } from './providers'
import Nav from '@/components/Nav'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh-CN" suppressHydrationWarning>
      <body>
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  )
}
